name: Deploy Recipe Microservices

on:
  push:
    branches:
      - test

jobs:
  deploy:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        include:
          - service: "create-recipe-microservice"
            port: 4001
          - service: "update-recipe-name-microservice"
            port: 4002
          - service: "update-recipe-ingredients-microservice"
            port: 4003
          - service: "update-recipe-steps-microservice"
            port: 4004
          - service: "get-recipe-by-id-microservice"
            port: 4005
          - service: "list-all-recipes-microservice"
            port: 4006
          - service: "delete-recipe-microservice"
            port: 4007
          - service: "list-user-recipes-microservice"
            port: 4008
          - service: "recipe-modification-permission-microservice"
            port: 4009

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build Docker Image
        run: |
          docker build -t ${{ matrix.service }} ./${{ matrix.service }}
          docker save ${{ matrix.service }} > ${{ matrix.service }}.tar

      - name: Copy Docker Image to EC2
        uses: appleboy/scp-action@v0.1.4
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          source: "${{ matrix.service }}.tar"
          target: "~/"

      - name: Deploy on EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker load < ~/${{ matrix.service }}.tar
            docker stop ${{ matrix.service }} || true
            docker rm ${{ matrix.service }} || true
            docker run -d -p ${{ matrix.port }}:${{ matrix.port }} --name ${{ matrix.service }} ${{ matrix.service }}
